# -*- coding: utf-8 -*-
"""Code_To_Convert_Into_Cartoon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cOzTyO7NYHa9nBvwky0qasEM3RqQymKb
"""

#importing libraries
import cv2
import numpy as np

#reading image
img = cv2.imread('/content/WhatsApp Image 2022-04-23 at 8.35.56 PM.jpeg')

# Convert the image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

gray = cv2.medianBlur(gray, 5)

edges = cv2.Canny(gray, 50, 150)

color = cv2.bilateralFilter(img, 9, 250, 250)

cartoon = cv2.bitwise_and(color, color, mask=edges)

from google.colab.patches import cv2_imshow

# Display the original and cartoon images side by side
cv2_imshow(img)
cv2_imshow(cartoon)
cv2.waitKey(0)
cv2.destroyAllWindows()

pip install opencv-python --upgrade